version: '3.8'

services:
  webapp1:
    image: webapp1:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    